### ISSUE TITLE
I don't see any source for some of the classes in enterprise source zip

### ISSUE THREAD

**Issue by garpinc** [Captain-P-Goldfish/scim-for-keycloak#103]
For instance: de.captaingoldfish.scim.sdk.server.endpoints.authorize.Authorization

**Comment by Captain-P-Goldfish** [comment]
this is part of the OpenSource project: https://github.com/Captain-P-Goldfish/SCIM-SDK

**Comment by garpinc** [comment]
Which version would be appropriate for enterprise version i'm using?

**Comment by Captain-P-Goldfish** [comment]
This is noted on the versions table on the main -page at https://scim-for-keycloak.de
