### ISSUE TITLE
I can't seem to get authentication for scim working

### ISSUE THREAD

**Issue by garpinc** [Captain-P-Goldfish/scim-for-keycloak#104]
I put the access token in bearer token and attempted to access the scim endpoint but it says I'm not authenticated. If I turn off authentication on resource type then it works so there must be something going wrong. Can you tell me where to put a breakpoint on the keycloak server side to verify that the token is getting where it needs to go?

**Comment by Captain-P-Goldfish** [comment]
Have you assigned a client?
Documented here: https://scim-for-keycloak.de/documentation/administration/realm-management
Summary: **Enable Access to SCIM**

**Comment by garpinc** [comment]
I think I figured it  out and it worked
