### ISSUE TITLE
ResourceTypes and Realm Assignment Tabs are empty - Remote SCIM Provider Configuration

### ISSUE THREAD

**Issue by saravanad** [Captain-P-Goldfish/scim-for-keycloak#109]
Hi @Captain-P-Goldfish ,

We have a Local Keycloak running and We have the SCIM-SDK Spring Boot Samples that were available from your repository as well running. We are working on the Usecase of Pushing the User/Group from Keycloak to Spring boot. 

We have done the Remote SCIM Provider Configuration in the Keycloak. After saving the Configuration and clicking on the Load Provider Configuration, We got all the tabs. However the Resource Types Tab and Realm Assignment Tabs are empty. 
<img width="525" alt="image" src="https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/3892196/07ff55aa-3118-4484-9ecd-2e045e3753fa">
![image](https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/3892196/2cb1689f-501b-4a0a-b7f6-306ff4ac3275)

The Schema tab is coming up with the data.
![image](https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/3892196/e947bf6f-9ebf-4219-80b2-a53e4a23324f)

Any pointers on how to get the data in the Resource Types Tab and Realm Assignment Tabs, so that we can complete the Sync Configuration.

Thanks in advance for your support.

Thanks,
Saravana

**Comment by Captain-P-Goldfish** [comment]
Hi this is a known problem. Currently only fixed in version "kc-23-2.0.1-SNAPSHOT". Could you try this version if it works for you?

**Comment by saravanad** [comment]
Thanks @Captain-P-Goldfish  for the clarification. Can you let me know where to get this snapshot version of Keycloak? In the releases section, i only find 23.0.X and not 23.2

**Comment by Captain-P-Goldfish** [comment]
![kc-23-2 0 1-SNAPSHOT](https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/3079540/33af2887-0074-49a9-a6b4-d47a57fb8c84)

**Comment by Captain-P-Goldfish** [comment]
I have temporarily removed the SNAPSHOT version due to a serious bug. I will fix this bug and add the artifact again.

**Comment by Captain-P-Goldfish** [comment]
okay, fixed the bug and and added the SNAPSHOT release again, now under version "kc-23-2.1.0-SNAPSHOT"

**Comment by saravanad** [comment]
Thanks @Captain-P-Goldfish with the new jar, we are able to view the Resource Type Tab with the Data. However the Realm Assignment Tab is still showing empty. Any other configuration that we could be missing?

**Comment by Captain-P-Goldfish** [comment]
Hi this should be an authorization issue.
I would expect that the user you are using also does not see any realms in the "Realm Management" configuration, correct?
This is because a user can assign a SCIM client configuration only to a realm to which the user has SCIM configuration access. In other words: if the user has no `scim-admin`-role to a specific realm the user will not be able to assign the configuration to a specific realm.

**Comment by saravanad** [comment]
Thanks @Captain-P-Goldfish IT is working. After setting the roles properly, we are able to view the tabs.

**Comment by saravanad** [comment]
Thanks for the support
