### ISSUE TITLE
SCIM and SSO Handling - Automatic Linking of User Created through SCIM and SSO

### ISSUE THREAD

**Issue by saravanad** [Captain-P-Goldfish/scim-for-keycloak#116]
Hi @Captain-P-Goldfish ,

This is not an issue on the scim jar, more like know how request, not sure how to raise that separately, hence raising it in Issue category 

From OKTA(IDP), the users are pushed to Keycloak via SCIM. OKTA is also used for Single Sign On(SSO) and Keycloaks acts as a Identity Broker, between our application and OKTA which act as a Identity Provider(IDP).  When users are logged in for the first time, they are re-directed to Review Profile page in Keycloak, upon filling that, keycloak detects that there is already an user account with the similar name and whether it needs to link it.

<img width="791" alt="image" src="https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/3892196/b725146a-8872-41ee-b283-6db127d1709d">

When the User clicks on Add to Existing Account, then it ask for Authentication. Since the User is authenticated via OKTA, we would not be able to authenticate the user in keycloak directly. Hence we are unable the link the user account.

The work around that we have now is as an Admin User, try to link the account by going Users->(select specific User)->Identity Provider Link and manually linking by giving the username created through SCIM and well as through OKTA as shown below

<img width="419" alt="image" src="https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/3892196/bc556579-d3dd-447b-aed5-f987110f29f8">

Could you please share any insights on how this can be handled? Any idea on how to link the user accounts automatically at the time creation of users through SCIM.

Thanks,
Saravana

**Comment by Captain-P-Goldfish** [comment]
You can do this by changing the authentication-flow.
Copy the first-broker-login-flow and replace the subflow `Copy of first broker login First broker login-Conditional OTP` for the two steps `Detect existing broker user` and `Automatically set existing user`. If you do this the user will not be asked for authentication if the accounts are linked.

**Comment by saravanad** [comment]
Thanks @Captain-P-Goldfish. This worked.

**Comment by bentonjimmy** [comment]
@Captain-P-Goldfish any chance you could share a screenshot of the Authentication Flow or an export of it?  That would help clarify the setup.

**Comment by Captain-P-Goldfish** [comment]
![screen](https://github.com/user-attachments/assets/ef279c1b-f9a5-4ca4-95d5-17715ee7e8b6)
