### ISSUE TITLE
Group Member Sync Failure

### ISSUE THREAD

**Issue by saravanad** [Captain-P-Goldfish/scim-for-keycloak#118]
Hi @Captain-P-Goldfish ,

We are using the Synchronization mechainsm of syncing group/User. Both of them are working fine. However when we try to sync members of the group using the Below UI

<img width="673" alt="image" src="https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/3892196/e5686c94-6cbc-4676-b024-3e7ae3410de1">

we get the following exception in the keycloak.

<img width="690" alt="image" src="https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/3892196/6ba09e25-4cb3-436a-8326-63b4bd79fa6c">

We tried to verify whethe the external ID are set for all the users  and groups. They seem to be set for all.

Any ideas/pointers of how to debug this further would be really helpful.

Thanks,
Saravana

**Comment by Captain-P-Goldfish** [comment]
please try again with version `kc-23-2.2.0-free-SNAPSHOT`. If the error does still occur I will have a closer look

**Comment by saravanad** [comment]
Tried with the latest version. It is working. Thanks @Captain-P-Goldfish
