### ISSUE TITLE
email not present in response from /Users

### ISSUE THREAD

**Issue by strannik19** [Captain-P-Goldfish/scim-for-keycloak#12]
using 1.8.3. users in keycloak have the email field populated, but its not showing up when i GET /Users. is there something that i missed?

**Comment by Captain-P-Goldfish** [comment]
Sorry but this is not enough information. Which version of scim-for-keycloak do you use? The version you pointed out refers to the SCIM-SDK version.
And how exactly do you mean this? If a user is created the email is stored but not returned on the get-endpoint?

**Comment by strannik19** [comment]
keycloak version: 11.0.3. i'll get back to you on the plugin version. i'm assuming its the latest version that supports 11.0.3.
so i have users created already in keycloak  
![image](https://user-images.githubusercontent.com/12424124/120616945-f23ab800-c459-11eb-8b8d-c31495516df1.png)
when i GET /Users/1d8488b2-e033-40eb-8185-8d9e4cc42891, i only get this:
```
{
    "id": "1d8488b2-e033-40eb-8185-8d9e4cc42891",
    "userName": "fred@example.com",
    "name": {
        "familyName": "Johnson",
        "givenName": "Fred"
    },
    "active": true,
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
    "meta": {
        "resourceType": "User",
        "created": "2021-05-27T14:44:47.329Z",
        "lastModified": "2021-05-27T14:44:47.329Z",
        "location": "..."
    }
}
```

**Comment by Captain-P-Goldfish** [comment]
Just took a look into the source code and true. This is still an active bug. I am going to fix it in the next few days. Is it possible for you to update to a newer keycloak version?

**Comment by strannik19** [comment]
thanks for the update! they keycloak version itself is outside of my area of influence :) as i understand, it will be updated in the near future, but no concrete time frames are known

**Comment by strannik19** [comment]
currently, 11-b1 version is deployed. whats the best way to deploy this fix?

**Comment by Captain-P-Goldfish** [comment]
In order to prevent you from waiting any longer I added a new tag "kc-11-b2" that has the email problem fixed. But that is the only fix

**Comment by strannik19** [comment]
since then, keycloak has been updated to v12 and the kc-12-b2 release doesn't have this fix. is this something that you can add please? thanks!

**Comment by Captain-P-Goldfish** [comment]
Is an update not possible?
Its kinda hard to maintain bug fixes on several versions. Or would it be possible for you to provide a pull-request on kc-12 branch? I
