### ISSUE TITLE
Endpoint Authentication Method Issue

### ISSUE THREAD

**Issue by DL-YYA** [Captain-P-Goldfish/scim-for-keycloak#120]
Hi, I know that the standard way of endpoint authentication is to put the generated token in the Authorization header of the HTTP request and prefix it with "Bearer". However, there are some cases where it may be required to configure a username and password. 

So I was wondering if it is possible to implement the scim flow by providing username and password in the initiated request? If so, how do I do it? Thanks for your help.

**Comment by Captain-P-Goldfish** [comment]
Which API are you referencing?
SCIM Client or SCIM Server?

- SCIM Server supports only the authentication mechanisms by keycloak and this won't change.
- SCIM Client does support several authentication mechanisms. See Screenshot:

![Unbenannt](https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/3079540/4fb5b1ca-ad3f-4119-b47d-7d227213355c)

The `API KEY` selection can also be used to add specific custom headers to the HTTP request if required.
