### ISSUE TITLE
Checksum incorrect - kc-24-2.2.1-free

### ISSUE THREAD

**Issue by belerovon** [Captain-P-Goldfish/scim-for-keycloak#121]
Hi Pascal 

the checksum is incorrect of 24-:2.2.1

2024-08-05 13:02:46,722 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.ValidationFailedException: Validation Failed:
     1 changesets check sum
          META-INF/scim-changelog.xml::2.2.0::pascal_knueppel was: 9:41565ae6a688edfff8adcbbb80f61b4d but is now: 9:00954dea9016ae1b765c9b0db28d7af9

2024-08-05 13:02:46,722 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Validation Failed:
     1 changesets check sum
          META-INF/scim-changelog.xml::2.2.0::pascal_knueppel was: 9:41565ae6a688edfff8adcbbb80f61b4d but is now: 9:00954dea9016ae1b765c9b0db28d7af9

**Comment by Captain-P-Goldfish** [comment]
Hi,
may it be that you did have the 2.2.0-SNAPSHOT version installed before switching to the new release?

In that case please follow these steps.
I forgot to upload it version 2.2.1:

```
If you have used the version 2.2.0-SNAPSHOT before you will need to execute the following SQL statements before
reinstalling:

alter table SCIM_REMOTE_PROVIDER drop column SEND_LOCAL_ID_IN_REQUEST;
alter table SCIM_REMOTE_PROVIDER drop column SEND_EXTERNAL_ID_IN_REQUEST;
alter table SCIM_REMOTE_PROVIDER drop column INVERT_EXCLUDE_ROLES; -- this column might not exist
delete from databasechangelog_scim_jpa_e where id = '2.2.0';

if you install the SNAPSHOT version for the first time you do not need to execute these statements.
```

**Comment by belerovon** [comment]
Thanks thats it
