### ISSUE TITLE
Assign a user a role based on a SCIM attribute

### ISSUE THREAD

**Issue by bentonjimmy** [Captain-P-Goldfish/scim-for-keycloak#129]
My question might be similar to this: https://github.com/Captain-P-Goldfish/scim-for-keycloak/issues/89 but I don't fully understand the replies in that thread.

We have an attribute provided in our SCIM feed for a Job Code.  I'm wondering if I can use the Job Code's value to assign a user to a role.  Right now, I only see the ability to use a SAML attribute to assign a role.  Is it possible to do this with a SCIM attribute?  

A more concrete example:
User 1 has Job Code 12345 so is assigned role1.
User 2 has Job Code 111111 so is assigned role2.

**Comment by Captain-P-Goldfish** [comment]
Something like this is not possible with the SCIM plugin.
I think what you are searching for is a custom Keycloak Plugin that does this. If a user is updated and gets a job-code x it should receive role z.
