### ISSUE TITLE
SCIM Connection Details is not persisted in GUI

### ISSUE THREAD

**Issue by dmitry-mightydevops** [Captain-P-Goldfish/scim-for-keycloak#131]
![image](https://github.com/user-attachments/assets/35f65a2e-e718-48f7-9b15-7ac23cd59a0c)

Changing Request timeout or socket timeout and then clicking save - shows the same values after the savbe op.

**Comment by dmitry-mightydevops** [comment]
Upgraded to latest kc-26-2.4.0, but still the same issue
![image](https://github.com/user-attachments/assets/3e802bf7-9596-4ec4-8341-870a3081e137)
it reported as saved, but then after reload still shows 10/10/5

**Comment by Captain-P-Goldfish** [comment]
thanks for reporting this. Just fixed it and it will be released in the next version
