### ISSUE TITLE
Does scim-for-keycloak rise keycloak events when provisions new user or updates group members etc?

### ISSUE THREAD

**Issue by pr0peller** [Captain-P-Goldfish/scim-for-keycloak#14]
Hello,

I'm not sure is this the right place to ask this question, but I would like to ask does scim-for-keycloak rise keycloak events when provision new user or updates group members? Is there some extra configuration which I am missing? I can see those activities in the logs but no any admin event. I am publishing all keycloak admin events to RabbitMQ queue and would like to be able to react to those events.
Thank you in advance for you answer :)

**Comment by Captain-P-Goldfish** [comment]
Good point. I actually missed to fire admin events. I thought the JpaRealmProvider would fire these kind of event without double checking it. And what to say? I just did and it does not. So admin events are currently not triggered by this implementation.

**Comment by pr0peller** [comment]
Any plans to add the admin events to the implementation? :)

**Comment by Captain-P-Goldfish** [comment]
Done, but only for keycloak 14.
commit is on master-branch feel free to check :-)

**Comment by Captain-P-Goldfish** [comment]
it was simply possible to cherry pick the commit to kc13 branch so its available now for keycloak 13 also

**Comment by pr0peller** [comment]
Thank you very much for that. I can update scim-for-keycloak and continue my work :)

Thank you so much one more time. :)
