### ISSUE TITLE
Keycloak 15: Menu isn't there

### ISSUE THREAD

**Issue by mkg20001** [Captain-P-Goldfish/scim-for-keycloak#20]
I've built and deployed kc-14-b3 and installed the .ear file

There are logs that say that it's loading the module

```
Aug 02 21:26:41 xstage standalone.sh[337787]: 21:26:41,689 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.s4yrny2n5d7yi9kv4vbhjwri55yc4dfr-scim-for-keycloak-kc-14-b3.ear.scim-for-keycloak-server.jar" is using a private module ("org.keycloak.keycloak-services") which may be changed or removed in future versions without notice.
```

But still the menu isn't there

![image](https://user-images.githubusercontent.com/7735145/127926063-3e7a6439-a4df-4588-aa05-0fdc744d1bef.png)

Might be a change that is required for keycloak 15 support?

**Comment by Captain-P-Goldfish** [comment]
kc14 and 15 seem to be commpatible. In other words it works for me.
There are some things I can think of:

1. Did you select the scim-theme on realm master? (unfortunately it does not work if the scim-theme is selected in another theme than the master realm. Selecting it there will enable the SCIM-menu button for all realms)
2.  Did you reload the page in the  browser after selecting the theme?

**Comment by mkg20001** [comment]
Ah that was it, thank you it works now.

I think it's not mentioned in the readme, it should be added there.

**Comment by mkg20001** [comment]
Ah no wait I'm just too incompetent :sweat_smile:
