### ISSUE TITLE
JVM Ouf Of Memory error

### ISSUE THREAD

**Issue by mgr-atolcd** [Captain-P-Goldfish/scim-for-keycloak#22]
Hello,

We got an error after installing the plugin, and we don't know if it's the source plugin.

Have you ever encountered these errors?

![image006 (1)](https://user-images.githubusercontent.com/87488472/133044424-ba94d35f-cbf2-4c2a-b336-0c5897e33cf6.jpg)

![image008](https://user-images.githubusercontent.com/87488472/133043982-7ab5fb05-7218-4626-a633-16c738cfce30.jpg)

Thanks for your reply.

PS : We have these errors on the Keycloak server.

BR,

**Comment by Captain-P-Goldfish** [comment]
Sorry, but I have not enough information to tell if this would be the fault of the scim-for-keycloak api. This is also the first time I hear about such an error. 
But if this happened directly after the deployment my first guess would be that the deployment itself simply exceeded the maximum amount of available memory. But I am afraid I cannot give you any details on this. This is something that must be investigated more thoroughly. I would propose to use "jvisualvm" to track down the source of this. This tool has proven quite useful to me on such matters in the past.

**Comment by Captain-P-Goldfish** [comment]
is this still an issue or can I close this ticket?

**Comment by mgr-atolcd** [comment]
Hello, yes, you can close this ticket.

We have increased the resources allocated for Java and now everything is fine for this part.

Thank you for your attention.

BR
