### ISSUE TITLE
Using "Accept: application/json" header causes 406 Not acceptable error

### ISSUE THREAD

**Issue by xgp** [Captain-P-Goldfish/scim-for-keycloak#23]
I'm using the SCIM testsuite from here (https://github.com/wso2-incubator/scim2-compliance-test-suite), and I see that the SCIM endpoints respond with a "406 Not Acceptable" because their test client sets the "Accept: application/json" request header. This doesn't seem to be a violation of the spec. Is it possible to update the resources to allow clients to set this header?

**Comment by Captain-P-Goldfish** [comment]
Yes that is possible. I have to fix this within the SCIM-SDK. I got another open issue there and I guess I should be able to fix it this weekend.

**Comment by Captain-P-Goldfish** [comment]
release will have to wait. Circle-CI has currently some problems with the build-chain. But the build itself works perfectly. You should be able to use the head-commit to get it to work with keycloak 14 and 15
