### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by PeterSR** [Captain-P-Goldfish/scim-for-keycloak#28]
Hi! 

We are using Keycloak in Kubernetes and therefore use the Keycloak Docker image and Helm chart. 
Are there any plans on creating a Dockerfile that bundles Keycloak and scim-for-keycloak?

Thanks

**Comment by Captain-P-Goldfish** [comment]
HI I did not plan to create a docker-image here. Maintaining it would be a real pain and it is pretty simple deploying the scim-api into keycloak by just mounting the artifact into the deployments directory or using jboss-cli.
I am afraid you will need to generate your own Dockerfile that copies the artifact.

**Comment by PeterSR** [comment]
Hi! 
Thank you for your reply and I understand that it is a real pain to maintain. I think deep down I was looking for an easy way out since I not familiar with the Java eco-system, Jboss and the Java build and deployment process. I will do some proper learning about Java and create my own Dockerfile. Thanks!

**Comment by Captain-P-Goldfish** [comment]
I will add a simple manual to the wiki in the next few days

**Comment by PeterSR** [comment]
Thank you so much! I will let you know if I have any questions or comments :blush:
