### ISSUE TITLE
customize  schemas:extension

### ISSUE THREAD

**Issue by jorgecotrina** [Captain-P-Goldfish/scim-for-keycloak#29]
Hi @Captain-P-Goldfish 

I've to extend my user schema ("schemas: extension"), but can't find any examples.
Do i need to modify the source code or is there another method?

Thanks for this extension!

**Comment by Captain-P-Goldfish** [comment]
Currently I did not implement it in scim-for-keycloak. It is easily possible by making source-code changes but it is also be possible to create a configurational approach. Since the schema-defintions can be exchanged during runtime.
