### ISSUE TITLE
Can you post only final ear file

### ISSUE THREAD

**Issue by runticm** [Captain-P-Goldfish/scim-for-keycloak#33]
Hi
I wondering if there is a way to only download ear files instead of building the whole process. It would be awesome to provide binaries. Thanks

**Comment by Captain-P-Goldfish** [comment]
I actually did not want to put the artifacts but I think I can do this in the future.

**Comment by runticm** [comment]
Thanks

**Comment by Captain-P-Goldfish** [comment]
New release is out: 

https://github.com/Captain-P-Goldfish/scim-for-keycloak/releases/tag/kc-16-b1

**Comment by runticm** [comment]
Excellent :)
