### ISSUE TITLE
Theme files missing

### ISSUE THREAD

**Issue by Tristanden** [Captain-P-Goldfish/scim-for-keycloak#37]
Hi, 

it seems that the latest tag misses the resource files for the scim admin theme. I have seen that you removed all these files in commit 731c0f6a94b4a5009f7ab4bd0e562ad294fdaf66 and that the artifact you have pushed contains a "scim2" folder but I can't find anything like this in the repo. Did I miss something ? 

Thanks

**Comment by Captain-P-Goldfish** [comment]
this was an accident. I will add some assertions to prevent this from happening again.
The next release will come this evening.

**Comment by Tristanden** [comment]
Thanks for your fast feedback !
