### ISSUE TITLE
Provide binaries for releases.

### ISSUE THREAD

**Issue by zambrovski** [Captain-P-Goldfish/scim-for-keycloak#43]
Hi,

is there a reason why you don't provide a packaged EAR of the library?

I could easily provide you some GitHub Action script which would at least build the latest master/develop branch. In the same time, I could tell you how to publish it to OSS Maven Central.

What do you think?

Cheers,

Simon

**Comment by Captain-P-Goldfish** [comment]
If you look at the README.MD there is a new section regarding this issue. From version kc-16-b1 onwards I will provide artifacts in the releases-section.
