### ISSUE TITLE
XSD issue with scim-for-keycloak-kc-16-b3.ear

### ISSUE THREAD

**Issue by mmouly** [Captain-P-Goldfish/scim-for-keycloak#46]
Hello,

Perhaps an error on my side because I'm new on this.
Here is how I tried to deployed: 
1/ Get v16.1.1 from https://www.keycloak.org/downloads.html
2/ Then  pushed https://github.com/Captain-P-Goldfish/scim-for-keycloak/releases/download/kc-16-b3/scim-for-keycloak-kc-16-b3.ear on keycloak-16.1.1/standalone/deployments/

Deployment is failing and complaining on dbchangelog-3.9.xsd
[server.log](https://github.com/Captain-P-Goldfish/scim-for-keycloak/files/8039774/server.log)

**Comment by mmouly** [comment]
many thanks Captain for the quick reply ;-)

**Comment by emacdona** [comment]
Just going to paste the complete error message here in case someone (like me) tries Googling for it :-)

Caused by: java.io.FileNotFoundException: /src/main/resources/META-INF/dbchangelog-3.9.xsd (No such file or directory)

Thanks, btw. This was exactly the problem I was having.
