### ISSUE TITLE
Case (in)sensitive PATCH operations

### ISSUE THREAD

**Issue by petkocfc** [Captain-P-Goldfish/scim-for-keycloak#5]
Hi @Captain-P-Goldfish,
we started using scim-for-keycloak version 1.8.2 on keycloak version 9.0. 
Everything worked fine until we started provisioning users over Azure SCIM where we have issue with case sensitive PATCH operations defined in [PatchOp](https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/6d0a59d15b457b206365bfb02ac3fede94ac7fc6/scim-sdk-common/src/main/java/de/captaingoldfish/scim/sdk/common/constants/enums/PatchOp.java).

When users are patched over Azure SCIM operations have a first letter upper case (Add, Replace, Remove), 
and in the Azure [documentation](https://docs.microsoft.com/en-us/azure/active-directory/app-provisioning/use-scim-to-provision-users-and-groups#understand-the-aad-scim-implementation) under "general guidelines" point six it's stated
"Don't require a case-sensitive match on structural elements in SCIM, in particular PATCH op operation values, as defined in [section 3.5.2](https://tools.ietf.org/html/rfc7644#section-3.5.2). AAD emits the values of op as Add, Replace, and Remove."

This case sensitive check where problem lies is in PatchHandler - [handlePatchOp](https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/6d0a59d15b457b206365bfb02ac3fede94ac7fc6/scim-sdk-server/src/main/java/de/captaingoldfish/scim/sdk/server/patch/PatchHandler.java#L142).

Is it possible to make it case insensitive in [PatchOp](https://github.com/Captain-P-Goldfish/SCIM-SDK/blob/6d0a59d15b457b206365bfb02ac3fede94ac7fc6/scim-sdk-common/src/main/java/de/captaingoldfish/scim/sdk/common/constants/enums/PatchOp.java#L36) in order to be compatible with Azure SCIM?

**Comment by petkocfc** [comment]
Would it be too much of a trouble for you to release it sooner? 
Since we have a project relying on the fix that is due end of March 😅

**Comment by Captain-P-Goldfish** [comment]
I think I can do that. I will provide it until the end of next week then.

**Comment by Captain-P-Goldfish** [comment]
Release is out

kc-12-b2

**Comment by petkocfc** [comment]
Hi @Captain-P-Goldfish,
just to say that we are constantly testing SCIM with Keycloak on Azure from the moment you released the new version and it's working smoothly. 

Thank you.
