### ISSUE TITLE
User provisioning from KC to AAD

### ISSUE THREAD

**Issue by jkovaliov** [Captain-P-Goldfish/scim-for-keycloak#57]
Hello. Is it possible to provision users **FROM** Keycloak **TO** Azure AD using this plugin? Or does it work from AAD to KC only?

**Comment by Captain-P-Goldfish** [comment]
Hey,
currently the implementation offers only one way: from AAD to KC.
See also: https://github.com/Captain-P-Goldfish/scim-for-keycloak/issues/3

keycloak is currently in a state of drastic rebuilding. There are also alternative user storage implementations that will be available soon that might allow to do provisioning into the other direction as well but I haven't checked the details yet
