### ISSUE TITLE
Git release tags kc-12-b1 and kc-11-b1 point to the latest SNAPSHOT

### ISSUE THREAD

**Issue by meden** [Captain-P-Goldfish/scim-for-keycloak#6]
Hello, it seems that both release tags actually point to the same commit bumping the release to the next snapshot ` kc-12-b2` (3d6dca6).

They should point to respective release commit instead:
* `kc-11-b1` -> 6032b19efb331357c484e66bb714a919cfe99122
* `kc-12-b1` -> c452d75d8491ae9f37a94d06951bc95dd7b6a8c4

Thanks for your work, I'll hope to be able to test it soon!

**Comment by Captain-P-Goldfish** [comment]
thx for reporting this... seems I got a little slacky there. I am going to fix this later today

**Comment by Captain-P-Goldfish** [comment]
Okay I just managed to take a closer look. But the tags seem to be set correctly. Either that or I simply not getting the issue here. Could you please clarify for me?

If I checkout `git checkout tags/kc-12-b1`  I am landing on commit `c452d75` just as you pointed out. And if I check in the commit histroy this is exactly the commit "Release to kc-12-b1"

**Comment by meden** [comment]
Well, I'm a little confused...

On GitHub:
![image](https://user-images.githubusercontent.com/824351/110774119-bda1d080-825d-11eb-83e0-3d35f1a9fdf4.png)

On my machine, right after a clone:
![image](https://user-images.githubusercontent.com/824351/110774765-723bf200-825e-11eb-942a-94a4f0a2f0b3.png)

And doing `git checkout tags/kc-12-b1`:
![image](https://user-images.githubusercontent.com/824351/110775021-bd560500-825e-11eb-8365-4aaebb469cbd.png)

(But I would just simply do `git checkout -b kc-12-b1`).

Am I missing something?

**Comment by Captain-P-Goldfish** [comment]
I do not know how this happened. When I look at my local repository it looks like this:
![git-commands](https://user-images.githubusercontent.com/3079540/110839648-15632a80-82a4-11eb-9104-c1f317cb7718.png)

But after a new checkout I can verify what you see. Big question is how this happened...

**Comment by Captain-P-Goldfish** [comment]
Okay the tags should be fixed now.
Thanks. I would have never noticed this since my local setup was okay...
