### ISSUE TITLE
Azure AD not connecting to Keycloak SCIM endpoint

### ISSUE THREAD

**Issue by a-syde** [Captain-P-Goldfish/scim-for-keycloak#62]
Hi there,

I could follow the guide on connecting Azure AD till the point where I had to test the connection between Azure AD and Keycloak.

The connection doesn't work for some reason.

I believe that there is an error in the following endpoint: `https://<SERVER>/auth/realms/<REALM>/scim/v2`
When I test the endpoint using Postman, I get this error
![image](https://user-images.githubusercontent.com/23285542/188416716-d4c4c2c6-4344-43e4-b729-46de7a1040a9.png)

### Azure error:
![image](https://user-images.githubusercontent.com/23285542/188417965-f6240e3e-ab43-40b7-873b-e67a0c71c7cb.png)

### Background info:
Keycloak: Keycloak-X version 18.0.2
provider version: kc-18-b1

### Two questions:
- does the error have something to do with the provider?
- what is the "Secret Token" in Azure Portal? Is it the access token that I get after authenticating against the client or is it the secret in clients -> <CLIENT> -> credentials -> secret?
![image](https://user-images.githubusercontent.com/23285542/188418364-1e326d78-4fe8-4213-bc73-240eb149aa11.png)

**Comment by Captain-P-Goldfish** [comment]
hi. The URL changed from keycloak 16.1.1 to keycloak 17.0.0.
Simply remove the "auth" from the URL. Instead of  `https://<SERVER>/auth/realms/<REALM>/scim/v2` try `https://<SERVER>/realms/<REALM>/scim/v2`

**Comment by a-syde** [comment]
@Captain-P-Goldfish thanks a lot for your quick reply!

Unfortunately it didn't work.

Now I get a different error testing with Postman

```
<html>

<body>
	<h1>Resource not found</h1>
</body>

</html>
```

**Comment by Captain-P-Goldfish** [comment]
I am having no problems so far:

this one works just fine for me. Is your access token still valid:

Keycloak: 18.0.2

```http
POST https://localhost:8443/realms/master/scim/v2/Users
Content-Type: application/scim+json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIza1gzeVJEVXZZanA5TVcwaGRWbjFuc21fRXBOaHJtZnBtd3FnWDlxb3BFIn0.eyJleHAiOjE2NjI0MDc2MjgsImlhdCI6MTY2MjM5MzIyOCwianRpIjoiZjBlNzBkYjQtMDZmOC00YzUzLTliNzUtN2ZiYWQ5MWI3M2IwIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6ODQ0My9yZWFsbXMvbWFzdGVyIiwiYXVkIjpbIm1hc3Rlci1yZWFsbSIsImFjY291bnQiXSwic3ViIjoiNTVlZWM4MGQtZWNmYy00M2IyLWIyODktMmE3M2U1OTgzZTBmIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2NpbS1jbGllbnQiLCJzZXNzaW9uX3N0YXRlIjoiNTYxNGJlMmItNjQxYy00NjdiLTk5NzUtMjU0YzI4NjZjZDljIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJjcmVhdGUtcmVhbG0iLCJkZWZhdWx0LXJvbGVzLW1hc3RlciIsIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7Im1hc3Rlci1yZWFsbSI6eyJyb2xlcyI6WyJ2aWV3LXJlYWxtIiwidmlldy1pZGVudGl0eS1wcm92aWRlcnMiLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwic2NpbS1hZG1pbiIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjU2MTRiZTJiLTY0MWMtNDY3Yi05OTc1LTI1NGMyODY2Y2Q5YyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW4ifQ.GJx2RE-aYqgaEdemH94n9gXKF3IyOV4sLn48AXOUCY8ONQwuv__YQ8djciHu_ZY_TrUV_cAaEkkhKlmoUydi8eP7lRgwRMi5gpEnQzqLp01aOPBmGFKaExI5sMc5NxxqY3b17vl29xzmUIERJ-YaH6IrNT6JbkwyPLHy7ykr7IfknpIm9XCy1Es1dNrZCBwIgMFjQH3YEGB1EBX7TfSSefg8OxCM8wyoN6DxlmbaGUgUnD4WnPPaJadzh6CmHzWloweL0AM5vvy0dX0ftOyxm1mYFK-mil7kI-_JN3aWWxK-EXNqw1ux9bdaZZes8fSHvP5eXPGDtBcSW79mhlvadQ

{
    "userName": "test"
}
```

**Comment by a-syde** [comment]
Hmm - this is so weird!

I am using the same Keycloak version but I definitely get different results.
 
A bit more information.
I am using the official Docker image `quay.io/keycloak/keycloak:18.0.2`.
I am able to build the custom Docker image with the provider.

I do get results when creating a user
```
{
    "schemas": [
        "urn:ietf:params:scim:schemas:core:2.0:User"
    ],
    "id": "28e08ef2-4a0b-4e88-8b4a-1829ea0c89e0",
    "userName": "test",
    "active": false,
    "meta": {
        "resourceType": "User",
        "created": "2022-09-05T16:09:20.603Z",
        "lastModified": "2022-09-05T16:09:20.603Z",
        "location": "https://<SERVER>/auth/realms/master/scim/v2/Users/28e08ef2-4a0b-4e88-8b4a-1829ea0c89e0"
    }
}
```

**The strange part is** that my URL is the following: `https://<SERVER>/auth/realms/master/scim/v2/Users` (with **`/auth`** )

Your URL doesn't have `/auth` as you mentioned. 

If I remove `/auth` I get 404 `Resource not found`

I would like to understand why Azure AD cannot establish a connection to my Keycloak with and without `/auth`

**Comment by Captain-P-Goldfish** [comment]
I can think of only two plausible explanations.

1. You are accessing a URL pointing to a reverse-proxy that is not properly configured and that points to a keycloak of version 16.1.1 or below.
2. You added a context-path to the keycloaks configuration within keycloak.conf the adds the "/auth" to the front.

I am not sure if the second is even possible did not try it so far. But there is at least a poorly documented property `hostname-path` that lets suggest that it is possible.

**Comment by Lpirela92** [comment]
Hello @a-syde / @Captain-P-Goldfish

"I could follow the guide on connecting Azure AD till the point where I had to test the connection between Azure AD and Keycloak."

I am working on this, and it would be great to have this guide mentioned above. Can you please share it? Thanks a lot.

**Comment by Captain-P-Goldfish** [comment]
the guide mentioned above would be this one: https://github.com/Captain-P-Goldfish/scim-for-keycloak/wiki/Use-with-Microsoft-Azure-AD
