### ISSUE TITLE
Assigning group to user

### ISSUE THREAD

**Issue by KalyaniBharatha** [Captain-P-Goldfish/scim-for-keycloak#64]
Hi,
Regarding adding members to group, we can do it using Patch request right, but its not with put (updating the group) or post(creating the group). is it has any reason? and also can we add extra parameters to create user request body ?

**Comment by Captain-P-Goldfish** [comment]
I have difficulties following your issue. Do you have problems using PUT and POST to update and create groups? This should work. What errormessages do you get when trying?

**Comment by KalyaniBharatha** [comment]
Hi , actually i want to assign groups to users. Iam trying to do by adding groups parameters to  /Users request. User is creating but group is not assigning.
![image](https://user-images.githubusercontent.com/36667030/191480578-f5e6e778-c29c-464c-ba2a-c5a2ad5cf294.png)

**Comment by Captain-P-Goldfish** [comment]
this is expected behaviour. 
If you look closely at the users-schema you will find the definition of the groups-attribute is read-only
```json
{
      "name": "groups",
      "type": "complex",
      "description": "A list of groups to which the user belongs,\neither through direct membership, through nested groups, or dynamically calculated.",
      "mutability": "readOnly",
      "returned": "default",
      "uniqueness": "none",
      "multiValued": true,
      "required": false,
      "caseExact": false,
      ...
```

You need to do it the other way around. You must add the user to a specific group so a patch request on the groups endpoint would be appropriate:

```json
{
      "schemas" : [ "urn:ietf:params:scim:api:messages:2.0:PatchOp" ],
      "Operations" : [ {
        "path" : "members",
        "op" : "add",
        "value" : "{\"value\": \"0289cf0a-98f2-45c1-9db0-a70935d01ffc\", \"type\": \"User\"}"
      } ]
    }
```

**Comment by KalyaniBharatha** [comment]
Thank you. Issue resolved
