### ISSUE TITLE
feature request: custom attribute mapping

### ISSUE THREAD

**Issue by RiskManagementGroup** [Captain-P-Goldfish/scim-for-keycloak#67]
It would be nice with a way to customize the attribute mapping, so for example instead of

phoneNumbers: {  "value" : "+4511279865",  "type" : "mobile",  "primary" : false }

it could be mapped to

mobile: "+4511279865"

**Comment by Captain-P-Goldfish** [comment]
this feature will be available to certain degree with the release of 2.0.0 at https://scim-for-keycloak.de
The version 2.0.0 is still in development though.
