### ISSUE TITLE
Keycloak legacy distribution

### ISSUE THREAD

**Issue by hoeggi** [Captain-P-Goldfish/scim-for-keycloak#68]
I tried to get the extension working with keycloak:18.0.0-legacy (the jboss distribution). I couldn't get it to work because of some problems with liquibase (first because of `liquibase.secureParsing` and second because of some error when trying to read the liquibase migration files from the jar). 

Is this something that should still be supported or is Quarkus the only supported distribution? If the legacy jboss distribution should still be supported I can provide logfiles and stacktraces for those errors.

**Comment by Captain-P-Goldfish** [comment]
The Wildfly distribution is no longer supported since the quarkus distribution is does require another deployment setup. You can see this when taking a look into the deployment files:

![Unbenannt](https://user-images.githubusercontent.com/3079540/195770917-7672720e-829e-4d27-919d-6dc116926bb1.PNG)
