### ISSUE TITLE
Ship source code artifact in a "delomboked" form

### ISSUE THREAD

**Issue by meden** [Captain-P-Goldfish/scim-for-keycloak#7]
Please, when generating source code artifact, perform a ["delombok" step](http://anthonywhitford.com/lombok.maven/lombok-maven-plugin/usage.html), so to avoid discrepancies between bytecode and source, which makes debugging much harder.

![image](https://user-images.githubusercontent.com/824351/112114323-3a1aa480-8bb8-11eb-90c8-9d7a8c9ba6b8.png)

Thanks!

**Comment by meden** [comment]
Sorry, this was meant for SCIM-SDK project, although I guess it is valid for this one too... Should I open it there too?

**Comment by Captain-P-Goldfish** [comment]
Please move the ticket to SCIM-SDK project

**Comment by Captain-P-Goldfish** [comment]
this ticket is closed in SCIM-API and will be released soon. So I am closing this.
