### ISSUE TITLE
Patching email of type work via Azure provisioning not working.

### ISSUE THREAD

**Issue by iSellgren** [Captain-P-Goldfish/scim-for-keycloak#73]
Hi, when i try to patch a users email, via Azure's provisioning I recived the following error message: 

```
Web Response: {"detail":"No target found for path-filter 'emails[type eq \"work\"].value'","schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"status":400,"scimType":"noTarget"}
```

When trying to perform the same request using Postman with the following body:

```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "path": "emails[type eq \"work\"].value",
            "value": "updatedEmail@microsoft.com"
        }
    ]
}
```

I reviced the same error message as i did from Azure as I mention earlier, however when using the following operation, the patch work as inteded and I reviced an  the email address was updated.  

```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "path": "emails",
            "value": [{ "type": "work","value": "updatedEmail@microsoft.com", "primary": true }]
        }
    ]
}
```

I also found out that it was possible to patch a user's phoneNumber via an Operation similar to the email operation that failed.

```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ],
    "Operations": [
        {
            "op": "replace",
            "path": "phoneNumbers[type eq \"work\"].value",
            "value": "+1 234 567 8915"
        }
    ]
}
```

How come that it's possible to patch and change the user's phoneNumber via Azure, but not the email field when performing similar operations? Is this behavior intended, or what could cause this error message.

**Comment by Captain-P-Goldfish** [comment]
I need to do some tests. But I can currently only think of three possible scenarios:

1. The get-endpoint is not entering the type value into the email-object
2. the type-value contains other characters e.g. whitespaces
3. the type-value was never set for the email

I will later check these three possibilites. 

One question. May it be that the email with type "work" is marked as primary by any chance?

**Comment by Captain-P-Goldfish** [comment]
alright that is probably the culprit: 

```java
List<Email> emails = getAttributeList(Email.class, AttributeNames.RFC7643.EMAILS, userModel);

    Optional.ofNullable(userModel.getEmail()).ifPresent(email -> {
      // remove emails that are marked as primary in favor of the email property attribute of the user
      emails.removeIf(MultiComplexNode::isPrimary);
      emails.add(Email.builder().primary(true).value(email).build());
    });
```

If the email we are talking about is the primary email the type value is getting lost on retrieving it eventhough it is stored in the database. That would explain why the target is not found.

I will later write a fix here.

**Comment by iSellgren** [comment]
Thanks for the fast replay, correct the email with type work is marked as primary.
