### ISSUE TITLE
Performance Problem

### ISSUE THREAD

**Issue by csbrogi** [Captain-P-Goldfish/scim-for-keycloak#78]
Hi
we have scim-for-keycloak running with AZURE and we have currently ~9.000 Users in a realm. Wenn the AZURE SCIM sends a request 

`https://keycloak.../auth/realms/REALM/scim/v2/Users?filter=userName+eq+%22AzureAD_Test-bdd952ba-be0b-47d4-b4c9-be5afee16d2d%22 `
(the user doesn't exist. it is sent to test finctionality)
the request runs in a timeout.
I commented out the part in the userrequest, which adds the group-membership to the user object, and then I get a timely response.
In the realm there is no group.

**Comment by Captain-P-Goldfish** [comment]
this is a known issue and I already tackled that problem in a complete redevelopment of this problem. If you look at the README.MD https://github.com/Captain-P-Goldfish/scim-for-keycloak I am planning to release it next month. That is if I am able to get it finished until then. But I think that I am right on schedule with my plan.
