### ISSUE TITLE
Easy to use docker image?

### ISSUE THREAD

**Issue by WestFarmer** [Captain-P-Goldfish/scim-for-keycloak#80]
Do we have a docker image? or add docs about how to deploy to docker based keycloak install?

**Comment by Captain-P-Goldfish** [comment]
Hi there is no docker image, but the installation is very easy.
The Open Source version is currently compatible with keycloak 18 and 19. For later versions like 20 and 21 I just created the enterprise version but I am still struggling with some legal stuff before I am able to provide it.

Download the artifact in the releases section, put it into you` "${keycloak.home}/providers` directory and execute `${keycloak.home}/bin/kc.sh build`. That is basically all to the installation. For further instructions consult the README.MD of this project.

This Open Source version is also only supporting the old-administration console. The enterprise version provides a complete separated administration console that was embedded into the keycloak to bypass the extensibility problem of the new keyclock ui.
