### ISSUE TITLE
Attribute named "pattern" in resource schema User  under userName Attribute

### ISSUE THREAD

**Issue by manju754** [Captain-P-Goldfish/scim-for-keycloak#84]
We are trying to integrate keycloak with other SCIM provider with keycloak acting as SCIM Server and other provider as SCIM Client.
SCIM Client has Users and Groups which needs to be provisioned to Keycloak as part of SCIM.

While we are establishing the connectivity between other provider and keycloak for SCIM Provisioning.

The Other provider is failing with invalid attribute named "pattern" in resource schema User under userName attribute.

I have pasted the sample userName definition for reference.

{ 
"id": "urn:ietf:params:scim:schemas:core:2.0:User", 
"name": "User", 
"description": "User Account", 
"attributes": [ 
{ 
"name": "id", 
"type": "string", 
"multiValued": false, 
"description": "Unique identifier for the SCIM Resource as defined by the Service Provider.", 
"required": true, 
"caseExact": true, 
"mutability": "readOnly", 
"returned": "always", 
"uniqueness": "server" 
}, 
{ 
"name": "externalId", 
"type": "string", 
"multiValued": false, 
"description": "A String that is an identifier for the resource as defined by the provisioning client.The service provider MUST always interpret the externalId as scoped to the provisioning domain.", 
"required": false, 
"caseExact": true, 
"mutability": "readWrite", 
"returned": "default", 
"uniqueness": "none" 
}, 
{ 
**"name": "userName",** 
"type": "string", 
"multiValued": false, 
"description": "A service provider's unique identifier for the user, typically\nused by the user to directly authenticate to the service provider.Each User MUST include a non-empty userName value. This identifier\nMUST be unique across the service provider's entire set of Users.", 
"required": true, 
"caseExact": false, 
"mutability": "readWrite", 
"returned": "default", 
"uniqueness": "server", 
**"pattern": "^(?!\\s*$).+"** 
},.  ot
 
 
 Is this the valid attribute from SCIM Resource Schema USER?
 
 Does it adhere to RFC standards?
 
 can you shed some light on this ??

**Comment by Captain-P-Goldfish** [comment]
This is actually not an attribute defined by SCIM. It is a customized attribute added by the underlying SCIM SDK that is used to limit the characters usable for the userName attribute.^(?!\s$).+
If this is causing a problem I will fix this for the enterprise version that is released soon. 
If you are able to build the project scim-for-keycloak project yourself you can fix it for the time being by adding this line of code:

## class ScimConfiguration
```java
ResourceType userResourceType = resourceEndpoint.registerEndpoint(new UserEndpointDefinition(new UserHandler()));
userResourceType.setFeatures(ResourceTypeFeatures.builder().autoFiltering(true).autoSorting(true).build());
ScimResourceTypeEntity userResourceTypeEntity = resourceTypeService.getOrCreateResourceTypeEntry(userResourceType);
resourceTypeService.updateResourceType(userResourceType, userResourceTypeEntity);
userResourceType.getSchemaAttribute(AttributeNames.RFC7643.USER_NAME).get().setPattern(null); <--- this line
```

**Comment by Captain-P-Goldfish** [comment]
I will also add a fix into the SCIM-SDK that the custom attributes will not be returned by default anymore

**Comment by Captain-P-Goldfish** [comment]
I am currently not working anymore on the Open Source version. Which is why I tried to give you the fix from above.
My goal is to provide an access for a free starter version until end of april. The enterprise version has still to wait due to organizational issues.
Which version of Keycloak are you using?
The starter kit will support version 18 to 20

The product is basically finished. It hangs simply on organization...

**Comment by manju754** [comment]
We are using the keycloak version 20.03

**Comment by manju754** [comment]
We tried building using maven with the fix you had provided above.

However, I am facing some issue while building the jar 
which states that the object we are expecting is not the object we are getting in "UserResourceType"

userResourceType.getSchemaAttribute(AttributeNames.RFC7643.USER_NAME).get().setPattern(null); <--- this line

Above line is causing the problem
Getting below error while building using maven

[ERROR] /home/manju/dev-workspace/src/github.com/scim-for-keycloak/scim-for-keycloak-server/src/main/java/de/captaingoldfish/scim/sdk/keycloak/scim/ScimConfiguration.java:[86,21] method getSchemaAttribute in class de.captaingoldfish.scim.sdk.common.resources.base.ScimObjectNode cannot be applied to given types;
**[ERROR]   required: no arguments
[ERROR]   found: java.lang.String
[ERROR]   reason: actual and formal argument lists differ in length**

Can you shed some light on this? and help us in building the jar with the fix

**Comment by Captain-P-Goldfish** [comment]
sorry. Seems like a copy paste error hit us here:

```
userResourceType.getMainSchema().getSchemaAttribute(AttributeNames.RFC7643.USER_NAME).setPattern(null)
```

the line can be fixed like this

**Comment by Captain-P-Goldfish** [comment]
I am sorry for that. This was a bug in the SCIM SDK. I fixed it and provided a new release that should have everything fixed what is causing problems to you. 
https://github.com/Captain-P-Goldfish/scim-for-keycloak/releases/tag/kc-20-b1

**Comment by manju754** [comment]
Thanks @Captain-P-Goldfish That works like a Charm :)
