### ISSUE TITLE
email not present in response from /Users for kc-20-b1

### ISSUE THREAD

**Issue by AlexHung123** [Captain-P-Goldfish/scim-for-keycloak#85]
I use the kc-20-b1 for scim with keycloak, however, i cannot get the user email from the response.
The user in keycloak does have the email address. The keycloak version I used is keycloak-20.0.2.

![image](https://user-images.githubusercontent.com/42966282/235834128-07d60642-45e0-4416-9437-46d44a69d0ba.png)

![image](https://user-images.githubusercontent.com/42966282/235834270-79932fcb-7b5f-4240-8250-d82b13df7a8a.png)

Thank you very much

**Comment by AlexHung123** [comment]
Dear,

I rollback the code for getting email to kc-18-b1, now it can get the email address.

![image](https://user-images.githubusercontent.com/42966282/235841419-b68bb51c-12c8-4346-abef-f17a5cd55d7e.png)

![image](https://user-images.githubusercontent.com/42966282/235841455-7929957e-04c1-4cb6-b641-880e8bf3830e.png)

Thank you very much

**Comment by Captain-P-Goldfish** [comment]
Hi,
sorry for the late response.
Would it be possible for you to switch to the free-license of the new SCIM for keycloak project? The problem you are describing is resolved there.
https://scim-for-keycloak.de

**Comment by Captain-P-Goldfish** [comment]
the problem was found by the way and fixed in the newer versions at https://scim-for-keycloak.de/
