### ISSUE TITLE
Can this module POST user data to client applications? (like Django or any others)

### ISSUE THREAD

**Issue by kawashimaken** [Captain-P-Goldfish/scim-for-keycloak#88]
dear @Captain-P-Goldfish 
First, Thank you for your work on this project.

I noticed this reply in other issue(https://github.com/Captain-P-Goldfish/scim-for-keycloak/issues/57#issuecomment-1206853246),  however I just want to confirm if it is possible to send bulk data **FROM** keycloak(with scim-for-keycloak) when triggered by user creation/removal events or any others,  **TO** other clients/applications (say Django App or something by **POST** data to Django App  http://django_app_server_url/users )

If it can, where can I find the instructions to enable it? Thank you!

**Comment by Captain-P-Goldfish** [comment]
Hi, 
this is currently not possible, but it might be if it is possible to modify the hibernate configuration with custom plugins. I haven't checked if this is possible, yet. And I won't be able to check it for at least another four weeks.

**Comment by kawashimaken** [comment]
@Captain-P-Goldfish  Hi! Thank you for your reply! 
I guess it is also the similar to this one: https://github.com/Captain-P-Goldfish/scim-for-keycloak/issues/2#issuecomment-755158361   since it seems that it's part of the SCIM specification(https://datatracker.ietf.org/doc/html/rfc7642#section-2.3.1)  I understand it could be a matter of implementation. Thank you for all the time you put into this project, if this is implemented in the future I would love to try it out!  Thank you again and have a nice day!

**Comment by Captain-P-Goldfish** [comment]
this is still in development. The current progress can be seen on https://scim-for-keycloak.de. I am closing this ticket
