### ISSUE TITLE
Question about SCIM support coverage: Is the SCIM Admin console currently available?

### ISSUE THREAD

**Issue by EST-94** [Captain-P-Goldfish/scim-for-keycloak#94]
Hello.

While applying SCIM for keycloak, I have a two question regarding the function of the image attached below.

1. edit Resource Type schema extensions
2. SCIM Admin Console availability

![kc](https://github.com/Captain-P-Goldfish/scim-for-keycloak/assets/80741511/2d5c4250-2faf-464a-ad22-f36c59bebbe7)

The currently applied version is :
- keycloak-20 version and the corresponding scim jar package.

The SCIM theme can be applied in the version I installed, but the SCIM Admin console is not displayed on the welcome page, so I was unable to modify the schema extension through the console.

I would like to add or edit a schema other than 'urn:ietf:params:scim:schemas:extension:enterprise:2.0:User', 
but I cannot edit it because the corresponding button is disabled as shown in the image.

To apply this, refer to readme.md and https://scim-for-keycloak.de/documentation/introduction. This got me thinking:

_1. To fully apply SCIM functionality, I need to use version 21+.
2. Currently, SCIM-for-keycloak has been released up to kc20, so in order to use full functionality, the enterprise plan must be activated or a higher free package must be released._

Like the analogy above, is this feature not yet available? 
If there is a way to use this function, I would really appreciate it if you could let me know.

Best Regards,
Kim

**Comment by Captain-P-Goldfish** [comment]
Hi from the screenshot it is obvious that you are still using the OpenSource version and downloaded the plugin from github. You need to download it from https://scim-for-keycloak.de to get the correct version.

The OpenSource version does not support the same feature set and it is not possible to dynamically modify the schemas or schema-extensions.
The plugin was completely reimplemented in the new versions.

**Comment by EST-94** [comment]
Thanks Captain! 

Sorry for the inconvenience, but is there a link where I can download the enterprise version?

I confirmed that keycloak's latest version, version 23, can be downloaded from ' https://www.keycloak.org/downloads.html '.
but I could not confirm where I could download the corresponding scim-for-keycloak package, 'kc-23-1.2.0-enterprise'.
If I activate the enterprise plan, will a download link for the package be also provided?

Best Regards,
Kim

**Comment by EST-94** [comment]
Hello Captain.

As you said, I was mistaken. 
After logging in from that URL, there were jar files available for download under Account Information.

thank you. I hope you always stay healthy!

Best Regards,
Kim
